apiVersion: v1
kind: PersistentVolume
metadata:
  name: skpaul-nfs-pv
spec:
  storageClassName: skpaul-nfs-sc
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-share/kubernetes/skpaul.info
    server: 192.168.0.96
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skpaul-nfs-pvc
spec:
  storageClassName: skpaul-nfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skpaul-deployment
  labels:
    app: skpaul.info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skpaul.info
  template:
    metadata:
      labels:
        app: skpaul.info
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: skpaul-nfs-volume
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: skpaul-nfs-volume
        persistentVolumeClaim:
          claimName: skpaul-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: skpaul-svc
spec:
  selector:
    app: skpaul.info
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 80
  type: LoadBalancer
